services:
  conf-render:
    image: mshafer1/envsubst:envsubst_0.24.1@sha256:4fa05eaf6b5fc8a8fbc67276139eb55089506104539305dd361d85da14f731dc
    env_file:
      - .env
    restart: "no"
    volumes:
      - ./acme_dns_config/config.cfg:/var/acme-dns-config.cf:ro
      - acme_dns_config_store:/etc/acme-dns:rw
    command:
      - export USE_HEADER="${USE_HEADER:-true}" && cat /var/acme-dns-config.cf | envsubst | tee /etc/acme-dns/config.cfg

  backend:
    image: mshafer1/acme-dns-fork:acme-dns-fork_0.1.4@sha256:001001f57ff26ca1fe961cf414b6970ace65f6e32b8810fdd4d809504abe5826
    restart: unless-stopped
    depends_on:
      conf-render:
        condition: service_completed_successfully
    networks:
      internal:
        ipv4_address: 172.19.0.2
    volumes:
      - acme_dns_config_store:/etc/acme-dns:ro
      - ./acme_dns_data:/var/lib/acme-dns
  pub_dns:
    image: mshafer1/dnsmasq:dnsmasq_2.91@sha256:1821ba59b25fe8e6aba3535c32189e297a040a53f53858a924bd2989ed2b4671
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "${PORT_PREFIX}53:53/tcp"
      - "${PORT_PREFIX}53:53/udp"
    command:
      - dnsmasq -d
    volumes:
      - ./dnsmasq_config/dnsmasq.conf:/etc/dnsmasq.conf:ro
    networks:
      external:
      internal:
        ipv4_address: 172.19.0.3

  web:
    image: nginx:1.28.2-alpine3.23@sha256:5b4900b042ccfa8b0a73df622c3a60f2322faeb2be800cbee5aa7b44d241649e
    ports:
      - "${PORT_PREFIX}80:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      internal:
        ipv4_address: 172.19.0.4
      external:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/client_certs:ro

volumes:
  acme_dns_config_store:

networks:
  external:
    driver: bridge
  internal:
    driver: macvlan
    internal: true
    # no/default parent
    ipam:
      config:
        - subnet: "172.19.0.0/24"
          ip_range: "172.19.0.0/24"
          # no gateway
